# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'


target 'FirebaseTutorial' do
  use_frameworks!

   pod 'FirebaseAnalytics'
   pod 'FirebaseAuth'
   pod 'GoogleSignIn'
   pod 'FBSDKLoginKit'

end
